config/routes.rb
Rails.application.routes.draw do
  root to: 'reptiles#index'
  devise_for :users
  resources :records
  resources :reptiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/record.rb
class Record < ApplicationRecord
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: %i[show edit update destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show; end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit; end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_record
    @record = Record.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def record_params
    params.require(:record).permit(:memo, :fece, :clean, :handling, :shed, :bath, :tall, :weight, :day, :reptile_id)
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.slim
= form_for @record do |f|
  - if @record.errors.any?
    #error_explanation
      h2 = "#{pluralize(@record.errors.count, "error")} prohibited this record from being saved:"
      ul
        - @record.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :memo
    = f.text_field :memo
  .field
    = f.label :fece
    = f.number_field :fece
  .field
    = f.label :clean
    = f.number_field :clean
  .field
    = f.label :handling
    = f.number_field :handling
  .field
    = f.label :shed
    = f.number_field :shed
  .field
    = f.label :bath
    = f.number_field :bath
  .field
    = f.label :tall
    = f.text_field :tall
  .field
    = f.label :weight
    = f.text_field :weight
  .field
    = f.label :day
    = f.datetime_select :day
  .field
    = f.label :reptile_id
    = f.text_field :reptile_id
  .actions = f.submit

app/views/records/edit.html.slim
h1 Editing record

== render 'form'

=> link_to 'Show', @record
'|
=< link_to 'Back', records_path

app/views/records/index.html.slim
h1 Listing records

table
  thead
    tr
      th Memo
      th Fece
      th Clean
      th Handling
      th Sheds
      th Bath
      th Tall
      th Weight
      th day
      th Reptile
      th
      th
      th

  tbody
    - @records.each do |record|
      tr
        td = record.memo
        td = record.fece
        td = record.clean
        td = record.handling
        td = record.shed
        td = record.bath
        td = record.tall
        td = record.weight
        td = record.day
        td = record.reptile_id
        td = link_to 'Show', record
        td = link_to 'Edit', edit_record_path(record)
        td = link_to 'Destroy', record, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Record', new_record_path

app/views/records/new.html.slim
h1 New record

== render 'form'

= link_to 'Back', records_path

app/views/records/show.html.slim
p#notice = notice

p
  strong Memo:
  = @record.memo
p
  strong Fece:
  = @record.fece
p
  strong Clean:
  = @record.clean
p
  strong Handling:
  = @record.handling
p
  strong Shed:
  = @record.shed
p
  strong Bath:
  = @record.bath
p
  strong Tall:
  = @record.tall
p
  strong Weight:
  = @record.weight
p
  strong Reptile:
  = @record.reptile_id
p
  strong day:
  = @record.day

=> link_to 'Edit', edit_record_path(@record)
'|
=< link_to 'Back', records_path