config/routes.rb
Rails.application.routes.draw do
  root to: 'reptiles#index'
  devise_for :users
  resources :records
  resources :reptiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reptile.rb
class Reptile < ApplicationRecord
end

app/controllers/reptiles_controller.rb
class ReptilesController < ApplicationController
  before_action :set_reptile, only: %i[show edit update destroy]

  # GET /reptiles
  # GET /reptiles.json
  def index
    @reptiles = Reptile.all
  end

  # GET /reptiles/1
  # GET /reptiles/1.json
  def show; end

  # GET /reptiles/new
  def new
    @reptile = Reptile.new
  end

  # GET /reptiles/1/edit
  def edit; end

  # POST /reptiles
  # POST /reptiles.json
  def create
    @reptile = Reptile.new(reptile_params)

    respond_to do |format|
      if @reptile.save
        format.html { redirect_to @reptile, notice: 'Reptile was successfully created.' }
        format.json { render :show, status: :created, location: @reptile }
      else
        format.html { render :new }
        format.json { render json: @reptile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reptiles/1
  # PATCH/PUT /reptiles/1.json
  def update
    respond_to do |format|
      if @reptile.update(reptile_params)
        format.html { redirect_to @reptile, notice: 'Reptile was successfully updated.' }
        format.json { render :show, status: :ok, location: @reptile }
      else
        format.html { render :edit }
        format.json { render json: @reptile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reptiles/1
  # DELETE /reptiles/1.json
  def destroy
    @reptile.destroy
    respond_to do |format|
      format.html { redirect_to reptiles_url, notice: 'Reptile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reptile
    @reptile = Reptile.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def reptile_params
    params.require(:reptile).permit(:name, :birthday, :comeday, :image)
  end
end

app/helpers/reptiles_helper.rb
module ReptilesHelper
end

app/views/reptiles/_form.html.slim
= form_for @reptile do |f|
  - if @reptile.errors.any?
    #error_explanation
      h2 = "#{pluralize(@reptile.errors.count, "error")} prohibited this reptile from being saved:"
      ul
        - @reptile.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :birthday
    = f.datetime_select :birthday
  .field
    = f.label :comeday
    = f.datetime_select :comeday
  .field
    = f.label :image
    = f.text_field :image
  .actions = f.submit

app/views/reptiles/edit.html.slim
h1 Editing reptile

== render 'form'

=> link_to 'Show', @reptile
'|
=< link_to 'Back', reptiles_path

app/views/reptiles/index.html.slim
h1 Listing reptiles

table
  thead
    tr
      th Name
      th Birthday
      th Comeday
      th Image
      th
      th
      th

  tbody
    - @reptiles.each do |reptile|
      tr
        td = reptile.name
        td = reptile.birthday
        td = reptile.comeday
        td = reptile.image
        td = link_to 'Show', reptile
        td = link_to 'Edit', edit_reptile_path(reptile)
        td = link_to 'Destroy', reptile, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Reptile', new_reptile_path

app/views/reptiles/new.html.slim
h1 New reptile

== render 'form'

= link_to 'Back', reptiles_path

app/views/reptiles/show.html.slim
p#notice = notice

p
  strong Name:
  = @reptile.name
p
  strong Birthday:
  = @reptile.birthday
p
  strong Comeday:
  = @reptile.comeday
p
  strong Image:
  = @reptile.image

=> link_to 'Edit', edit_reptile_path(@reptile)
'|
=< link_to 'Back', reptiles_path